#!/usr/bin/env bash

RET=1
PARAMS=
SESSION="auto-$RANDOM$RANDOM"
until [ -z "$1" ]; do
    case "$1" in
        '-S')
            RET=1
            shift
            SESSION="$1"
            ;;
        '-r' | '-x')
            RET=255
            shift
            SESSION="$1"
            ;;
        *)
            PARAMS+=" $1"
            ;;
        esac
    shift
done

if [ -n "$PARAMS" ]
    then 
    while [ 1 ]; do
    case $RET in
        '1') #new session needed
            echo "Session '$SESSION'"
            ssh $PARAMS -t screen -U -l -S $SESSION
            RET=$?
            ;;
        '255') #restart session
            echo "Restart session '$SESSION'"
            ssh $PARAMS -t screen -U -l -xR $SESSION
            RET=$?
            if [ $RET = 255 ]; then
                sleep 1;
                fi
        ;;
        '0')
            echo "Session '$SESSION' done"
            exit 0
            ;;
        *)
            echo "Session '$SESSION' error"
            exit $RET
            ;;
        esac;
    done;
    else
        (   echo "${0} ssh-screen tool"         >&2;
            ssh 2>&1 | sed -e 's/ssh/ssc/g'     >&2;
            echo "           [-r session_name]" >&2;
            echo "           [-S session_name]" >&2;
        ) | cat;
fi;
